In [2]:
import pandas as pd

In [16]:
vendas = pd.DataFrame({
    "produto": ["notebook", "mouse", "teclado", "notebook", "mouse"],
    "preco": [4500, 120, 350, 4800, 150],
    "quant": [1, 2, 1, 1,  3],
    "uf": ["SP", "RJ", "RJ", "MG", "SP"]
})

vendas

    produto  preco  quant  uf
0  notebook   4500      1  SP
1     mouse    120      2  RJ
2   teclado    350      1  RJ
3  notebook   4800      1  MG
4     mouse    150      3  SP

In [18]:
vendas["total_produto_reais"] = vendas["preco"] * vendas["quant"]
resumo = vendas.groupby("produto").agg(
    preco_medio=("preco", "mean"),
    total_vendido=("quant", "sum"),     
    total_vendido_reais=("total_produto_reais", "sum"),     
)

resumo

          preco_medio  total_vendido  total_vendido_reais
produto
mouse           135.0              5                  690
notebook       4650.0              2                 9300
teclado         350.0              1                  350

In [20]:
pvt = vendas.pivot_table(
    index="produto", columns="uf", values="quant", aggfunc="sum", fill_value=0
)
pvt

uf        MG  RJ  SP
produto
mouse      0   2   3
notebook   1   0   1
teclado    0   1   0

In [21]:
# Merge / Concat

In [23]:
clientes = pd.DataFrame({
    "id": [1, 2, 3],
    "nome": ["Ana", "João", "Maria"],
})

compras = pd.DataFrame({
    "id": [1, 1, 3, 3, 3], 
    "valor": [100, 200, 50, 75, 90]
})

display(clientes)
display(compras)

   id   nome
0   1    Ana
1   2   João
2   3  Maria

   id  valor
0   1    100
1   1    200
2   3     50
3   3     75
4   3     90

In [25]:
dfm = clientes.merge(compras, on="id", how="left")
display(dfm)
dfm = clientes.merge(compras, on="id", how="right")
display(dfm)

   id   nome  valor
0   1    Ana  100.0
1   1    Ana  200.0
2   2   João    NaN
3   3  Maria   50.0
4   3  Maria   75.0
5   3  Maria   90.0

   id   nome  valor
0   1    Ana    100
1   1    Ana    200
2   3  Maria     50
3   3  Maria     75
4   3  Maria     90

In [27]:
df1 = pd.DataFrame({
    'A': ["A0", "A1"],
    'B': ["B0", "B1"]
}, index=[0, 1])
df2= pd.DataFrame({
    'A': ["A2", "A3"],
    'B': ["B2", "B3"]
}, index=[2, 3])

display(df1)
display(df2)

    A   B
0  A0  B0
1  A1  B1

    A   B
2  A2  B2
3  A3  B3

In [29]:
concat_vertical = pd.concat([df1, df2], axis=0)
display(concat_vertical)

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [33]:
df3 = pd.DataFrame({
    'C': ["C0", "C1"],
}, index=[0, 1])
concat_horizontal = pd.concat([df1, df3], axis=1)
display(concat_horizontal)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1